import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import {
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faCaretRight,
  faCaretDown,
  faTimes,
  faArrowLeft,
  faPlus,
  faInfo,
  faCheck,
  faUtensils,
  faCheese,
  faCalendarDays,
  faList,
  faTruck,
  faBars,
  faMoon,
  faSun,
  faLeaf,
  faFire,
  faClock,
  faMagnifyingGlass,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faCaretRight,
  faCaretDown,
  faTimes,
  faArrowLeft,
  faPlus,
  faInfo,
  faCheck,
  faUtensils,
  faCheese,
  faCalendarDays,
  faList,
  faTruck,
  faBars,
  faMoon,
  faSun,
  faLeaf,
  faFire,
  faClock,
  faMagnifyingGlass
);

export default FontAwesomeIcon;
