import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import {
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faCaretUp,
  faCaretLeft,
  faCaretRight,
  faCaretDown,
  faTimes,
  faArrowLeft,
  faArrowRight,
  faPlus,
  faInfo,
  faCheck,
  faUtensils,
  faCheese,
  faCalendarDays,
  faList,
  faBars,
  faMoon,
  faSun,
  faLeaf,
  faFire,
  faClock,
  faMagnifyingGlass,
  faBellConcierge,
  faMugSaucer,
  faFilter,
  faExclamation,
  faQuestion,
  faGear,
  faBoxOpen,
  faTags,
  faEllipsisVertical,
  faArrowUpRightFromSquare,
  faChartLine,
  faCalculator,
  faArrowDownAZ,
} from "@fortawesome/free-solid-svg-icons";

import { faClock as faRegularClock } from "@fortawesome/free-regular-svg-icons";

library.add(
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faCaretUp,
  faCaretLeft,
  faCaretRight,
  faCaretDown,
  faTimes,
  faArrowLeft,
  faArrowRight,
  faPlus,
  faInfo,
  faCheck,
  faUtensils,
  faCheese,
  faCalendarDays,
  faList,
  faBars,
  faMoon,
  faSun,
  faLeaf,
  faFire,
  faClock,
  faMagnifyingGlass,
  faBellConcierge,
  faMugSaucer,
  faFilter,
  faExclamation,
  faQuestion,
  faGear,
  faBoxOpen,
  faTags,
  faEllipsisVertical,
  faRegularClock,
  faArrowUpRightFromSquare,
  faChartLine,
  faCalculator,
  faArrowDownAZ
);

export default FontAwesomeIcon;
